name = "OpenPKPD"
uuid = "00000000-0000-0000-0000-000000000001"
version = "0.1.0"
authors = ["OpenPKPD Contributors"]

[deps]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"

[compat]
JuliaFormatter = "2.2.0"
julia = "1.10"
