name = "OpenPKPDCore"
uuid = "aa42e64f-7c0c-4f7e-9a43-9f30a48e1a32"
version = "0.1.0"
authors = ["shramish2057 <shramish4@gmail.com>"]

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DifferentialEquations = "7.17.0"
Distributions = "0.25.122"
JSON = "1.3.0"
SciMLBase = "2.131.0"
StableRNGs = "1.0.4"
StaticArrays = "1.9.16"
